CREATE TABLE dbo.Users (
  UserId INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(120) NOT NULL,
  Phone NVARCHAR(20) NOT NULL UNIQUE,
  Role NVARCHAR(20) NOT NULL CHECK (Role IN ('owner', 'customer')),
  BusinessName NVARCHAR(160) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Products (
  ProductId INT IDENTITY(1,1) PRIMARY KEY,
  Name NVARCHAR(160) NOT NULL,
  DesignCode NVARCHAR(50) NOT NULL UNIQUE,
  ImageUrl NVARCHAR(1000) NULL,
  BodyColor NVARCHAR(20) NOT NULL DEFAULT '#245a6b',
  AccentColor NVARCHAR(20) NOT NULL DEFAULT '#d9a441',
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.ProductVariants (
  VariantId INT IDENTITY(1,1) PRIMARY KEY,
  ProductId INT NOT NULL,
  Size NVARCHAR(40) NOT NULL,
  Weight NVARCHAR(40) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CONSTRAINT FK_ProductVariants_Products FOREIGN KEY (ProductId)
    REFERENCES dbo.Products(ProductId)
);

CREATE TABLE dbo.Orders (
  OrderId INT IDENTITY(1,1) PRIMARY KEY,
  OrderNo NVARCHAR(40) NOT NULL UNIQUE,
  CustomerName NVARCHAR(120) NOT NULL,
  Phone NVARCHAR(20) NOT NULL,
  Total DECIMAL(10,2) NOT NULL,
  Status NVARCHAR(30) NOT NULL DEFAULT 'Pending',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.OrderItems (
  OrderItemId INT IDENTITY(1,1) PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductId INT NULL,
  VariantId INT NULL,
  ProductName NVARCHAR(160) NOT NULL,
  DesignCode NVARCHAR(50) NULL,
  Size NVARCHAR(40) NOT NULL,
  Weight NVARCHAR(40) NOT NULL,
  Quantity INT NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  LineTotal AS (Quantity * Price) PERSISTED,
  CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId)
    REFERENCES dbo.Orders(OrderId)
);
